name: ESLint Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install ESLint and dependencies
        run: |
          npm install eslint@9.8.0
          npm install prettier
          npm install eslint-config-prettier
          npm install @microsoft/eslint-formatter-sarif@latest
          npm install @typescript-eslint/parser
          npm install @typescript-eslint/eslint-plugin
          npm install @stylistic/eslint-plugin
          npm install eslint-plugin-import
          npm install eslint-plugin-lit

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . \
            --config .eslintrc.js \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif || true
        continue-on-error: true

      - name: Upload SARIF if it exists
        if: always() && hashFiles('eslint-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true          
